version: '3.9'

services:
  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - '8090:8080'
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./files:/home/wiremock/__files
